### ISSUE TITLE
[Question] Usecases of this library for Spotify

### ISSUE THREAD

**Issue by abdulhannanali** [spotify/redux-location-state#10]
Hello Spotify Team,

I would like to know, any public use cases of this library for spotify if there are any, and you can share them with me. Thanks a lot :+1: From the idea, I guess it's for Shopify embeds to make them stateless and make it easier to do stateless customizations just through editing the urls.

**Comment by joshbDev** [comment]
hey @abdulhannanali , glad to answer! We build a lot of different sites, both internally and externally. A lot of times we'll have sites that change based on the state of where a user is at (think of a search site that has a lot of filters turned on), when a user clicks the back button, or deeplinks to a page, the state needs to be refreshed to reflect what the url state is, not the redux state. This library was built to keep both in line with one another. Hope that helps!

**Comment by atav32** [comment]
@abdulhannanali check out their blog post, https://labs.spotify.com/2017/08/10/thinking-of-state-in-a-world-of-urls/

-----

I actually think it'd be really helpful to link the blog post in the README
