### ISSUE TITLE
reducersWithLocation with Immutable.js object

### ISSUE THREAD

**Issue by AfonsoTsukamoto** [spotify/redux-location-state#21]
Hi! 
I was trying to use redux-location-state (RLS) with immutable.js and I kept running into a case where RLS would break my store everytime `REDUX-LOCATION-POP-ACTION` (back) was triggered.

The problem seems to be this Object.assign call: 
https://github.com/spotify/redux-location-state/blob/master/src/createReduxLocationActions.js#L45

If `locationToStateReducer` returns an Immutable.js object, then Object.assign breaks it.
Removing Object.assign seems to solve it.

Not sure if I'm doing something wrong here or if it is not supposed to work with Immutable.js (though it says it should on the [blogpost](https://labs.spotify.com/2017/08/10/thinking-of-state-in-a-world-of-urls/) )

----

To reproduce, using RLS/examples with immutable.js:

`yarn add immutable -D`

```javascript
// examples/src/reducers/counter.js
// Ensure the store is always working with Immutable.

import {fromJS} from 'immutable'
import {ACTIONS, INITIAL_STATE} from '../constants.js'

export default function counterReducer(state = fromJS(INITIAL_STATE), action) {
  const {type, payload} = action;
  switch(type) {
    case ACTIONS.INCREMENT_COUNTER:
      return state.update('count', (count) => count + payload.amount);

    case ACTIONS.DECREMENT_COUNTER:
      return state.update('count', (count) => count - payload.amount);

    default:
      return state;
  }
}
```

```javascript
// examples/src/location.js

import _ from 'lodash';
import {INITIAL_STATE} from './constants';

export function mapLocationToState(state, location) {
  switch(location.pathname) {
    case "/":
      // default to zero and get value from immutable store
      const { count } = location.query || { count: 0 };
      return state.set('count', count);

    default:
      return state;
  }
}

// dumb stateToParams so it knows how to get values form the store
export function stateToParams(initialState, currentState, location) {
  const count = currentState.get('count');
  return {
    location: {...location, search: `?count=${count}` },
    shouldPush: true
  };
}

export const paramSetup = {
  global: {
     count: {stateKey: 'count', type: 'number', options: {shouldPush: true}, initialState: INITIAL_STATE.count}
  }
};
```

```javascript
// examples/src/store.js

import compact from 'lodash/compact';
import {createStore, applyMiddleware} from 'redux';
import thunkMiddleware from 'redux-thunk';
import createLogger from 'redux-logger';
import {createReduxLocationActions} from '../../src/index';
// get the stateToParams dumb fn
import {mapLocationToState, paramSetup, stateToParams} from './location';

export default function createAppStore(reducer, history) {
  const loggerMiddleware = createLogger({collapsed: true});
  // pass own stateToParams fn
  const {locationMiddleware, reducersWithLocation} = createReduxLocationActions(paramSetup, mapLocationToState, history, reducer, stateToParams);

  const middleware = compact([
    thunkMiddleware,
    locationMiddleware,
    loggerMiddleware
  ]);

  return createStore(reducersWithLocation, applyMiddleware(...middleware))
}
```

The changes above won't work without the mentioned fix:

```javascript
// src/createReduxLocationActions.js
...
    reducersWithLocation: (() => {
      const locationReducer = (state, action) => {
        const {type, payload} = action;

        if (!payload) {return state;}
        if (LOCATION_POP === type) {
          if (payload.search) {
            payload.query = parseQuery(setupObject, payload);
          }
          // removed Object.assign here
          return payload ? locationToStateReducer(state, payload) : state;
        }
        return state;
      };

      return function combinedReducer(state, action) {
        const postReducerState = appReducer(state, action);
        const postLocationState = locationReducer(postReducerState, action);
        const hasChanged = postLocationState !== state;
        return hasChanged ? postLocationState : state;
      };
    })()
 ...
```

**Comment by AfonsoTsukamoto** [comment]
Ok, that makes sense. I'll be happy to submit the PR. I just removed the Object.assign on my tests but I'm guessing that might break some implementation if the locationToStateReducer returns something that is not an object, ie. we want to ensure that an object is returned - right?


Another thing, and this might be asking too much, but the stateToParams fn could also be made compatible with Immutable.js. Currently it just uses lodash to get the values from the store object but I can see 2 possible changes that would make it work with Immutable too:

- One would be to use immutable's functional `getIn` instead of lodash's `get`. It works with both Immutable objects and native objects.

- Other would be to allow an accessor fn to be passed on the config that would override lodash `get` if present.

I think the first would be good because it would be abstracted for the user but it would bring Immutable.js as a dependency, which is not ideal.
Second is simply a new config option, so it should keep backwards compatibility without any extra dependencies.

If you think any of them would make sense I would be happy to work on it.

**Comment by AfonsoTsukamoto** [comment]
That sounds great 👍 Would be a really nice add to the lib so please do ping me when in.

Given that, I guess all I have to do is removing the line -> https://github.com/spotify/redux-location-state/pull/22

There are no tests for `createReduxLocationActions` yet so I didn't add one.
Can add it though - let me know 👍

**Comment by AfonsoTsukamoto** [comment]
Since the actual problem is fixed+merged, feel free to close the issue. 
Still in the queue to be pinged for the stateToParams fixed though 👍

**Comment by joshbDev** [comment]
this was merged in
