### ISSUE TITLE
Add a way to remove a parameter when corresponding currentItemState does not exists

### ISSUE THREAD

**Issue by Benjaki2** [spotify/redux-location-state#27]
Something to keep QueryStrings minimal when a parameter isn't needed or you are still in the initial state.

Something like this:?
```
export const paramSetup = {
  global: {
    p: {
      stateKey: 'projection',
      options: {
        hideParamWhenEmpty : true
      }
    }
}
```
And in (stateToParams)
```
if (currentItemState || !options.hideParamWhenEmpty) {
  prev[encodeURIComponent(curr)] = encodeURIComponent(currentItemState);
}
```

Thanks for this awesome tool!

**Comment by joshbDev** [comment]
Hey Ben!

there is already code in place to not put an item on the url if it's in it's default state (https://github.com/spotify/redux-location-state/blob/master/src/stateToParams.js#L27). I was thinking that if your default is empty than it's fine not to have it but if the item is empty and that's not your default then you'd like to track it. Do you have another use case that you may want to exclude the empty state?

**Comment by Benjaki2** [comment]
Wow, how did I missed this. Thanks much! That is all I needed. 🤝
