### ISSUE TITLE
Put location object in store

### ISSUE THREAD

**Issue by Benjaki2** [spotify/redux-location-state#30]
I have a share component that needs to know when the `queryString` has been updated. It would be nice if there was a `location` object in the store or maybe even just dispatching an accessible `action-type` when the permalink updates (maybe there already is one?), would do the trick.

Currently doing this workaround:
```
history.listen((location) => {
    const newString = location.search;
    if (queryString !== newString) {
      queryString = newString;
      store.dispatch(updateQueryString(queryString)); // Keep queryString in redux-store
    }
});
```

**Comment by tsufiev** [comment]
Hi, we had the similar issue recently, maybe that could help: https://github.com/spotify/redux-location-state/issues/29

**Comment by Benjaki2** [comment]
Thanks @tsufiev . I don't think `LOCATION_POP` will work for my use case since we don't want to retain the history. Ideally we would need a new action type e.g. `LOCATION_REPLACE` to fire every time `history.replace(nextLocation)` is going to be changed.

**Comment by tsufiev** [comment]
That could be tricky, since history.replace() is fired each time a store value tracked by RLS is updated - you can end up in a loop here, i.e. store changed -> histore.replace() -> LOCATION_REPLACE action is fired -> store changed -> ...

**Comment by Benjaki2** [comment]
Wont fix

**Comment by joshbDev** [comment]
yeah sorry for the super late response on this (I was moving across the country), but it sounds like this was resolved :+1:
