### ISSUE TITLE
Make parseParams function more dynamic

### ISSUE THREAD

**Issue by Benjaki2** [spotify/redux-location-state#36]
## Feature request

**Suggestion**
Allow for a custom `parseParams` function or change `parseParams` function to only split at the first instance of an equal sign instead of all versions.

**Code example**
[from](https://github.com/spotify/redux-location-state/blob/master/src/helpers.js#L114)
`const split = queryparam.split('=');`
[To](https://stackoverflow.com/a/53527079/4589331)
`var split = queryparam.match(/^.*?(?==)|[^=\n\r].*$/gm);`

**Purpose**
The project I work on uses the syntax `somelink?someId(someIdFromArray=someValue, someIdFromArray=someValue)` and we are working off of a forked version of `redux-location-state` because of this issue

**Comment by joshbDev** [comment]
yap, great call. I'll try to get this in the next day or two. thanks for the suggestion!

**Comment by Benjaki2** [comment]
Awesome. Thanks!

**Comment by joshbDev** [comment]
this fix is in! just follow the README to use your own parser. Your code did what I had actually wanted it to do, but I didn't want to break how things currently were for other users, so I allowed the ability to pass in how you want to parse

**Comment by Benjaki2** [comment]
Awesome, its working! Thanks again
