### ISSUE TITLE
Prevent location object mutation

### ISSUE THREAD

**Issue by kyriiherman** [spotify/redux-location-state#42]
`history` object is shared between many libraries like `connected-react-router` and mutating this object may cause bugs.
Currently `redux-location-state` mutates `location` object inside history here:  https://github.com/spotify/redux-location-state/blob/f7c32571d43bb69cb9318ccbf02d92aa118e5c39/src/createReduxLocationActions.js#L50

PR: https://github.com/spotify/redux-location-state/pull/41

**Comment by joshbDev** [comment]
is in version 2.8.0
