### ISSUE TITLE
Bug: adding any key with null value cause Error

### ISSUE THREAD

**Issue by kyriiherman** [spotify/redux-location-state#43]
Error is caused by this code: https://github.com/spotify/redux-location-state/blob/595ccbde35c633012c595dabda265dc720d1407c/src/helpers.js#L99 because you try to call `toString()` method before check on `null`/`undefined`. 
Also this PR fixes checking for empty array (`valueString` can't be an array).
PR: https://github.com/spotify/redux-location-state/pull/44.

**Comment by joshbDev** [comment]
The fix is in version 2.8.1

**Comment by kyriiherman** [comment]
@joshbDev  thanks for such a quick responses 👍 I've also have a question about peer dependencies: why do you have `react`, `react-dom` and `redux-thunk` in your peer dependencies? Looks like redux is the only thing that you really need...

**Comment by joshbDev** [comment]
yeah honestly it's been several years since I initially wrote this, and it was part of a React app that I was writing at the time so I think I copied that over. I don't think it needs the ones you mentioned.

**Comment by kyriiherman** [comment]
cool, I've created a PR to update the peer deps list: https://github.com/spotify/redux-location-state/pull/45.
Could you please merge it?

**Comment by joshbDev** [comment]
sorry for the late reply, it's merged.
