### ISSUE TITLE
Mistake on example

### ISSUE THREAD

**Issue by samuthekid** [spotify/redux-location-state#7]
https://github.com/spotify/redux-location-state#isflags

where is:
the url will be ?p=bazz-bar
should be:
the url will be ?p=bazz-**bin**

**Comment by LucasCaixeta** [comment]
Yes, I thought the same :) 

if the url will be ?p=bazz-bar

the object resultant should be this (or not?):
```
{
  '/': {
    foo: {
      bazz: true,
      bar: true,
      bin: false,
    }
  }
}
```

**Comment by joshbDev** [comment]
@LucasCaixeta the original use case I built it for didn't need to track `false` values (which it probably should), I'll open another issue for that
